# Branch Protection Rules Configuration

# Main branch protection
main:
  required_status_checks:
    strict: true
    contexts:
      - build
      - test
      - security-scan
      - dependency-check
  required_pull_request_reviews:
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
  enforce_admins: true
  allow_force_pushes: false
  allow_deletions: false
  required_linear_history: true

# Develop branch protection
develop:
  required_status_checks:
    strict: true
    contexts:
      - build
      - test
      - security-scan
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
  enforce_admins: true
  allow_force_pushes: false
  allow_deletions: false
  required_linear_history: true

# Feature branch naming convention
branch_naming:
  pattern: ^(feature|bugfix|hotfix|release)/[a-z0-9-]+$
  error_message: "Branch names must follow the pattern: type/description (e.g., feature/user-authentication)" 